[eslint] Workaround for 9.0.0 update (#1144)
Set the ESLINT_USE_FLAT_CONFIG=false environment variable when running ESLint. This is to workaround the following errors after ESLint got updated to 9.0.0:

  Invalid option '--resolve-plugins-relative-to' - perhaps you meant '--ignore-pattern'?
  You're using eslint.config.js, some command line flags are no longer available. Please see https://eslint.org/docs/latest/use/command-line-interface for details.

Also disable the `no-floating-promise` plugin since it starts
failing with the following error in ESLint 9.0.0:

  TypeError: context.getScope is not a function