Suppress compiler warnings in PC/SC-Lite code (#70)
Compile winscard_svc.c with "-Wno-return-type" and debuglog.c with
"-Wno-format", so that the PC/SC-Lite code is able to build by the
current NaCl toolchain without warnings (any warnings are fatal).

This fixes the recent regression that prevented the code from
being compiled using the current pepper_47 SDK. Apparently, this
old SDK was updated at some point by Chromium authors without
public announcements, and the new toolchain produces compiler
warnings that were not present before.

In particular, this commit fixes the following fatal build errors:

  third_party/pcsc-lite/src/src/winscard_svc.c:809:1: error:
    control reaches end of non-void function
    [-Werror,-Wreturn-type]
  }
  ^

  third_party/pcsc-lite/src/src/debuglog.c:196:32: error:
    format specifies type 'long' but the argument has type
    'pthread_t' (aka 'struct __nc_basic_thread_data *')
    [-Werror,-Wformat]
  time_pfx, delta, time_sfx, thread_id,
                             ^~~~~~~~~